@extends('layout')
@section('content')
<div>
    <h1>Privacy policy</h1>
    <p>

        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eu dictum leo. Maecenas vestibulum tincidunt dictum. Mauris vitae metus at arcu cursus feugiat quis a sem. Praesent justo nibh, facilisis a nunc sit amet, pretium feugiat libero. Nunc nisl lacus, semper id luctus sed, condimentum sit amet tortor. Aenean sed luctus enim. Quisque non nibh leo. Sed maximus iaculis est a gravida. Suspendisse potenti. Morbi nec justo nisl. Proin sollicitudin massa vel aliquam tincidunt. Aenean tristique risus non blandit viverra. Suspendisse eleifend commodo metus, non luctus libero scelerisque quis. Donec dignissim enim a suscipit ullamcorper. In interdum velit et dui commodo, et porttitor velit molestie. Nulla vehicula blandit volutpat.

        Aliquam pulvinar eleifend nunc, sed blandit nunc pretium vitae. Praesent et aliquam felis. Mauris eget libero ultrices, auctor elit at, sagittis velit. Morbi sed nibh ac metus posuere dignissim. Quisque bibendum vitae risus sit amet vulputate. Vestibulum egestas nisl at felis ultrices, et elementum augue sollicitudin. Morbi feugiat, massa pretium mollis porttitor, ligula turpis volutpat nulla, in fringilla massa urna eget augue. Suspendisse ultricies enim nisi, ac efficitur diam pharetra sed. Nunc egestas pulvinar ante nec scelerisque. Fusce ullamcorper laoreet velit, non tincidunt ante accumsan at. Duis fringilla, neque non tristique ultricies, felis orci suscipit ex, id faucibus purus risus quis mi. Donec ante velit, ornare ut dui ut, condimentum facilisis leo.

        Nam at mattis metus. Proin blandit tempus lorem nec consequat. Cras odio nulla, convallis eget felis sit amet, rutrum tristique metus. Sed suscipit, nibh nec volutpat placerat, nisl urna tempus quam, vitae tempor eros arcu a massa. Aliquam ultricies venenatis orci, id sollicitudin augue mollis et. Aliquam erat volutpat. Sed imperdiet, lectus sit amet pretium scelerisque, tortor nisl feugiat tortor, in pretium neque neque id ligula. Cras eu eros quis tortor sagittis tincidunt. Sed molestie tristique nulla a tristique. Nulla a ante mattis, lobortis velit a, consectetur nibh. Nunc eget maximus libero, at consequat lacus. Nunc sit amet lectus elementum, pharetra nulla id, iaculis enim. Donec scelerisque urna ligula, et dignissim dui viverra sed.

        Quisque lobortis quam metus, id tristique tellus convallis non. Donec at augue vitae mi feugiat vulputate. Aliquam erat volutpat. Donec augue ligula, facilisis nec feugiat sit amet, ultricies blandit est. Donec vitae dui sed dolor venenatis porttitor et vel lacus. Quisque tincidunt ac orci et venenatis. Praesent sed fermentum dolor, et congue urna. Aenean congue mattis scelerisque. In hac habitasse platea dictumst. Vivamus sit amet imperdiet massa, non luctus lorem.

        Integer dignissim tempor erat ut imperdiet. Ut id erat sodales, facilisis nunc eu, semper justo. Ut eget venenatis augue. Vestibulum mollis velit vestibulum elit pulvinar feugiat. Nam ut nibh et est elementum blandit. Vivamus consequat condimentum accumsan. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam iaculis ultricies rutrum. Aenean sollicitudin gravida turpis et maximus. Donec ultrices, ligula nec porttitor dictum, enim nulla tempor massa, vitae aliquam elit eros ac nisi. Morbi pretium ullamcorper quam, sed tristique tellus dapibus sed. Quisque ac dolor vestibulum, volutpat nisl eget, cursus elit. Proin ut diam tincidunt, molestie enim vitae, dapibus felis. Aliquam accumsan purus a tellus gravida, ac consectetur lectus iaculis. Nunc tempus, ligula vitae aliquet dictum, libero ipsum commodo tellus, in placerat augue nisi eu sapien. Pellentesque ut feugiat nisl. </p>
</div>
@endsection